---
title:  "{{< iconify tabler:hexagon-letter-g-filled label=games >}} Games"
format:
    html:
        body-classes: games
---

Video games provide new opportunities for research in cognitive science research and societal impact. They offer rich situations that are ecologically more valid than traditional cognitive tests; they can scale up and allow to collect rich datasets from a large number of people from very diverse backgrounds--video games therefore have the potential to overcome critical limitations of traditional experimental cognitive science research.

Furthermore the effective use of public video games for cognitive science research requires the integration of various facets of cognitive science research that are typically studied separately (e.g., user experience, motivation, cognition). They also require a scientific theory of game design to translate our scientific understanding into concrete game experiences. 

## {{< fa eye >}}  Vision  
To make large-audience, high-quality video games a main driver of cognitive science research and societal impact.

## {{< fa flask >}}  Projects


### Cognitive Training Game
The scientific literature has highlighted multiple hypotheses to explain cognitive training. The Behaverse cognitive training game attempts to translate those hypotheses into concrete video game mediated interventions and test their efficacy in improving cognitive abilities. 

::: {.callout}
You can learn more about this project [here](/games/cognitive_training/).
:::

### Mathemarmite: Educational game to help children count
We released [**Mathemarmite**](https://mathemarmite.lu/) on the [Google Play](https://play.google.com/store/apps/details?id=org.xcit.mathemarmite&rdid=org.xcit.mathemarmite&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) and [App Stores](https://itunes.apple.com/us/app/mathemarmite/id1440061165?ls=1&mt=8), a mobile video game for 3-6 year old children, designed to study and improve early mathematical (in particular counting) and cognitive abilities. This game was nominated for Best social effect / game beyond entertainment at Game Connection 2019.


::: {.callout}
You can learn more about this project [here](https://mathemarmite.lu/).
:::

### Collaboration game prototypes
We are developing of video game prototypes to study and potentially train collaboration skills. 
