
## Assessments  {.assessment}


## {{< fa bullseye >}} About  {.assessment}
Assessments are activities designed by researchers to support the valid and reliable quantification of the psychological traits, abilities, and states of the people completing those activities. 

Assessments comprise most prominently (but not exclusively) computerized cognitive tests (e.g., memorizing a sequence of digits in the digit span test) and questionnaires (e.g., the big-5 personality questionnaire). 


## {{< fa eye >}} Vision  {.assessment}
The ultimate goal for Assessments is to build a solid understanding of the design of instruments and their relationships to cognition, user experience and behavior. It entails creating a curated collection of generative instruments that allow a comprehensive assessment of human cognition, experience and behavior.



##  {{< fa flask >}} Projects  {.assessment}
### Cognitive Assessment Engines
Behaverse comprises a large battery of cognitive tests covering a wide range of domains, including attentional, perceptual, cognitive and motor abilities. This battery consists of multiple Cognitive Assessment Engines which are highly customizable (including the instructions, tutorials and practice blocks). By configuring a specific Cognitive Assessment Engine it is possible to instantiate many different cognitive tests.

::: {.callout}
You can learn more about this project [here](https://www.behaverse.org/assessments/cognitive_tests/).
:::

### Questionnaires
Asking people questions is a major research method in behavioral and social sciences, be it via standardized questionnaires (e.g., a personality questionnaire) or context sensitive, targeted questions (e.g., experience sampling).

We created a questionnaire data model (decoupling the data structures and backend from the survey viewer). This allows us to display questions on different devices (e.g., survey in a web browser, an experience sampling prompt within a mobile video game) while maintaining coherent data structures, which greatly facilitates their processing and subsequent analyses.
We also curated a list of questionnaires that we modified to increase consistency and data quality. We also developed software to distribute our questionnaires online while being GDPR compliant, multilingual, and supporting the collection of event data (e.g., key strokes, mouse trajectory) using a consistent data model. Finally, we developed a questionnaire response data model to facilitate and streamline the analysis of questionnaire response data.

::: {.callout}
You can learn more about this project [here](https://www.behaverse.org/assessments/questionnaires.html).
:::


### Games
Video Games that collect behavioral data can support various forms of assessment. To learn more about our projects in this domain, visit the **Games** section of this website.


::: {.callout}
You can learn more about this project [here](https://www.behaverse.org/games/index.html).

:::