[project]
name = "behaverse.github.io"
version = "0.1.0"
description = "Behaverse.org Website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "quarto-cli>=1.6.42"
]
