---
title: Data
format:
    html:
        body-classes: data
---


## {{< fa bullseye >}}  About
Data is fundamental to science. The Data galaxy contains datasets, software systems, frameworks and protocols that handle everything related to data management and automated processing.

## {{< fa eye >}}  Vision
To make it easy, fast and fun to find, explore, download and process a wide range of standardized experimental datasets in cognitive sciences and related fields (including benchmark datasets). 

## {{< fa flask >}} Projects
### The Behaverse data standards
A major challenge in behavioral and cognitive sciences is to define a standardized way of structuring and naming data so as to facilitate its processing. We dedicated a lot of effort in defining such standards for different types of data. 

::: {.callout}
You can learn more about this project [here](/standards/index.qmd).
:::

### The Behaverse dataset collection / dataset library
We are developing a curated list of datasets, all formatted according to Behaverse data standards. These datasets may be used for additional analysis, for benchmarking computational models and for developing multitask models among other things.

::: {.callout}
You can learn more about this project [here](/data/datasets.qmd).
:::


### The Behaverse Data API
The Behaverse Data API offers solutions to find and download datasets that follow the Behaverse data standard. The data-api currently exists as a python library (an R version is in the planning). 

::: {.callout}
You can learn more about this project [here](https://behaverse.github.io/data-api).
:::
