---
title: "{{< iconify tabler:hexagon-letter-m-filled label=models >}} Models"
format:
    html:
        body-classes: models
        code-links:
            - text: CogText
              icon: github
              href: https://github.com/morteza/CogText
            - text: CogEnv
              icon: github
              href: https://github.com/morteza/CogEnv
            - text: CogPonder
              icon: github
              href: https://github.com/morteza/CogPonder
        other-links:
            - text: CogText Paper
              icon: file-text
              href: https://arxiv.org/abs/2203.11016
            - text: CogText Dataset
              icon: database
              href: https://huggingface.co/datasets/morteza/cogtext
            - text: CogEnv Paper
              icon: file-text
              href: https://2022.ccneuro.org/proceedings/0000205.pdf?pn=1198
            - text: CogPonder Paper
              icon: file-text
              href: https://2023.ccneuro.org/proceedings/0001148.pdf
---

Projects in Models focus on the analysis of empirical data to gain insights about the human mind and behavior. Models may comprise a wide array of projects including generic data analytical tools (e.g., IRT models), domain specific computational models (e.g., computational models of performance on the N-Back task), descriptive vs performing models (e.g., RL-agents performing tasks) as well as tools and environments to support the use of such models.

## {{< bi eye >}} Vision
To make computational modeling accessible to a larger audience; to make it easier to improve on existing models and test the quality and generalizability of computational models across a wide range of benchmark datasets; to make cognitive sciences a cumulative science.

##  {{< bi puzzle >}} Projects

### CogEnv
CogEnv is a virtual environment based on [AndriodEnv](https://arxiv.org/abs/2105.13231) that allows artificial agents to complete the exact same tasks as in human studies. More specifically, typical reinforcement learning agents can be trained in CogEnv to perform tasks that are commonly used in cognitive psychology, such as the N-Back task and the Stroop task. CogEnv is designed to be a flexible and extensible platform that can be used to study [a wide range of cognitive tasks](/assessments/index.qmd) and to compare the performance of artificial agents to human participants.

::: {.callout}

To read more about this project, see [CogEnv paper](https://2022.ccneuro.org/proceedings/0000205.pdf?pn=1198) and [CogEnv repository on GitHub](https://github.com/morteza/CogEnv).

:::


### CogPonder
CogPonder is a flexible, differentiable model of cognitive control that is inspired by the Test-Operate-Test-Exit (TOTE) architecture in psychology and the PonderNet framework in deep learning. CogPonder functionally decouples the act of control from the controlled processes by introducing a controller that wraps around any end-to-end deep learning model and decides when to terminate processing and output a response, thus producing both a response and response time.


::: {.callout}

To read more about this project, see [CogPonder paper](https://2023.ccneuro.org/proceedings/0001148.pdf) and [CogPonder respository on GitHub](https://github.com/morteza/CogPonder).

:::



### CogText
CogText uses large language models to parse a large corpus of scientific documents to investigate the meaning and relationships between cognitive constructs on the one hand, and assessment instruments (i.e., cognitive tests) on the other.


::: {.callout}

To read more about this project, see [CogText paper on arXiv](https://arxiv.org/abs/2203.11016), [CogText repository on GitHub](https://github.com/morteza/CogText) and [CogText dataset on HuggingFace](https://huggingface.co/datasets/morteza/cogtext).

:::
